name: Hexlet CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci

      - name: Run tests and collect coverage
        run: npm test -- --coverage

      - name: Lint code
        run: npm run lint -- --fix

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        with:
          scannerVersion: "7.0.2.4839"
          projectBaseDir: ${{ github.workspace }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io 
          SONAR_PROJECT_KEY: zaikinale_frontend-project-46
          SONAR_ORGANIZATION: zaikinale-github